"""Analysis of the exploratory public-trace replay of the six study-B controllers.

Usage:
    python scripts/analyze_b5g_b.py [results/b5g_b]
Reads frontier_b5g_b.csv; writes tables/*.csv and SUMMARY_B5G_B.md. Not
pre-registered: the contrasts mirror H1 to H4 and the exploratory contrasts of
the synthetic test, over 6 cells (2 capacities x 3 budgets). Pairs are
(segment, model seed); pairs within a segment share the trace, so the per-
segment means are reported alongside the pooled paired tests.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from dsorch.experiments_b import frontier_points  # noqa: E402
from dsorch.stats import holm  # noqa: E402

BUDGETS = [30, 40, 50]
MIN_FRAC = 0.9          # a cell is analysed only if at least 90% of pairs reach the budget (as in the test)


def md(df: pd.DataFrame) -> str:
    df = df.reset_index() if not isinstance(df.index, pd.RangeIndex) else df
    cols = [str(c) for c in df.columns]
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(f"{v:.3g}" if isinstance(v, float) else str(v) for v in r) + " |")
    return "\n".join(out)
CONTRASTS = {
    "H1": ("Diffusion-RB", "GAN-RB"),
    "H2": ("Diffusion-RB", "QuantileMLP-RB"),
    "H3": ("Diffusion-RB", "Diffusion-JCSO"),
    "E1": ("QuantileMLP-RB", "QuantileMLP-JCSO"),
    "E3": ("QuantileMLP-RB", "GAN-RB"),
    "E4": ("QuantileMLP-JCSO", "Diffusion-JCSO"),
}
METHODS = ["Diffusion-RB", "GAN-RB", "QuantileMLP-RB", "Diffusion-JCSO", "GAN-JCSO", "QuantileMLP-JCSO"]


def diff(piv: pd.DataFrame, key: str) -> pd.Series:
    if key == "H4":
        sub = piv.reindex(columns=["Diffusion-RB", "Diffusion-JCSO", "GAN-RB", "GAN-JCSO"]).dropna()
        return (sub["Diffusion-RB"] - sub["Diffusion-JCSO"]) - (sub["GAN-RB"] - sub["GAN-JCSO"])
    a, b = CONTRASTS[key]
    sub = piv.reindex(columns=[a, b]).dropna()
    return sub[a] - sub[b]


def main() -> None:
    res = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "results" / "b5g_b"
    f = pd.read_csv(res / "frontier_b5g_b.csv")
    pts = frontier_points(f, BUDGETS, ["workload", "seed", "capacity", "method"])
    pts["segment"] = pts["seed"] // 10000
    tab = res / "tables"
    tab.mkdir(parents=True, exist_ok=True)
    pts.to_csv(tab / "points.csv", index=False)
    n_pairs = f["seed"].nunique()

    reach = pts.assign(reached=pts.miss_rate.notna()).groupby(["capacity", "budget", "method"])["reached"].sum()
    reach.reset_index().to_csv(tab / "reach.csv", index=False)
    means = pts.groupby(["capacity", "budget", "method"])["miss_rate"].agg(["mean", "std", "count"]).reset_index()
    means.to_csv(tab / "cell_means.csv", index=False)
    seg_means = pts.groupby(["segment", "capacity", "budget", "method"])["miss_rate"].mean().reset_index()
    seg_means.to_csv(tab / "segment_means.csv", index=False)

    rows = []
    for key in list(CONTRASTS) + ["H4"]:
        for (cap, bud), g in pts.groupby(["capacity", "budget"]):
            piv = g.pivot_table(index="seed", columns="method", values="miss_rate")
            d = diff(piv, key)
            seg = d.groupby(d.index // 10000).mean()
            analysed = len(d) >= np.ceil(MIN_FRAC * n_pairs)
            p = stats.ttest_1samp(d, 0.0).pvalue if analysed and d.std() > 0 else np.nan
            rows.append({"contrast": key, "capacity": cap, "budget": bud, "n_pairs": len(d), "analysed": analysed,
                         "mean_diff": d.mean(),
                         "sd_diff": d.std(ddof=1), "p": p, "segments_same_sign": int((np.sign(seg) == np.sign(d.mean())).sum()),
                         "n_segments": len(seg), **{f"segment_{int(s)}": v for s, v in seg.items()}})
    out = pd.DataFrame(rows)
    out["p_holm"] = np.nan
    for key, idx in out.groupby("contrast").groups.items():
        ok = out.loc[idx, "p"].notna()
        if ok.any():
            out.loc[out.loc[idx][ok].index, "p_holm"] = holm(out.loc[idx][ok]["p"].to_numpy())
    out.to_csv(tab / "contrasts.csv", index=False)

    piv = means.pivot_table(index=["capacity", "budget"], columns="method", values="mean")[METHODS]
    lines = ["# Public B5G trace replay of the six study-B controllers (exploratory)", "",
             "Generated by `scripts/analyze_b5g_b.py`. Not pre-registered. RB settings frozen from the synthetic "
             "validation run; nothing tuned on this trace.", "",
             f"Pairs (segment x model seed): {n_pairs}. Segments: {sorted(pts.segment.unique().tolist())}.", "",
             "## Mean miss rate (%) at matched over-reservation", "", md(piv.round(2)), "",
             "## Budget reach (pairs reaching the budget)", "",
             md(reach.unstack("method")[METHODS]), "",
             "## Contrasts (first minus second; Holm over 6 cells per contrast)", "",
             md(out[["contrast", "capacity", "budget", "n_pairs", "analysed", "mean_diff", "p_holm",
                     "segments_same_sign"]].round(4)), ""]
    (res / "SUMMARY_B5G_B.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines[6:12]))


if __name__ == "__main__":
    main()
