"""Study-B analysis (PREREGISTRATION_B v3.1 sections 5-6 with Amendment 1).

Usage:
    python scripts/analyze_b.py [results/study_b]
Writes <dir>/tables/*.csv and <dir>/SUMMARY_B.md from <dir>/frontier_b.csv.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from dsorch.analysis_b import analyse  # noqa: E402


def md(df: pd.DataFrame, fmt: str = "{:.3f}") -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(map(str, cols)) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(fmt.format(v) if isinstance(v, float) else str(v) for v in r) + " |")
    return "\n".join(out)


def main() -> None:
    res_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "results" / "study_b"
    frontier = pd.read_csv(res_dir / "frontier_b.csv")
    n_seeds = frontier["seed"].nunique()
    res = analyse(frontier, n_seeds)
    tab = res_dir / "tables"
    tab.mkdir(parents=True, exist_ok=True)
    for name, df in res.items():
        if df is not None:
            df.to_csv(tab / f"{name}.csv", index=False)
    t = res["cell_tests"].copy()
    lines = ["# Study B results", "",
             "Generated by `scripts/analyze_b.py` from `frontier_b.csv`. Do not edit by hand.", "",
             f"Test seeds: {n_seeds}. Primary outcome: miss rate (%) at matched over-reservation.", "",
             "## Hypothesis verdicts (section 6 decision rule)", "", md(res["verdicts"]), "",
             "## Per-cell tests (Holm within each hypothesis)", "",
             md(t[["hypothesis", "workload", "capacity", "budget", "n", "analysed", "mean_diff", "p", "p_holm"]]), "",
             "## Mean miss rate per controller and cell", "",
             md(res["cell_means"].pivot_table(index=["workload", "capacity", "budget"], columns="method",
                                              values="miss_rate").reset_index()), ""]
    (res_dir / "SUMMARY_B.md").write_text("\n".join(lines), encoding="utf-8")
    print(res["verdicts"].to_string(index=False))


if __name__ == "__main__":
    main()
